### ISSUE TITLE
Error:Cannot get property 'taskDependencies' on null object

### ISSUE THREAD

**Issue by dos1in** [jasonross/Nuwa#14]
使用1.5.0版本的com.android.tools.build:gradle时，调用apply plugin: "cn.jiajixin.nuwa"会提示
`Error:Cannot get property 'taskDependencies' on null object`
回滚到1.3.1后没有问题。

**Comment by jasonross** [comment]
@JChord  1.5还没适配，有空看一下，没想到1.5发的这么快，1.4都没relase，……

**Comment by htwahzs** [comment]
同样发现了。。

**Comment by htwahzs** [comment]
为什么仍然会报

**Comment by htwahzs** [comment]
仍然报错:
:app:nuwaClassBeforeDexDebug FAILED

**Comment by jasonross** [comment]
@htwahzs 这个问题还没改呢？

**Comment by dodola** [comment]
@JChord  @jasonross  好像是 [http://tools.android.com/tech-docs/new-build-system/transform-api](http://tools.android.com/tech-docs/new-build-system/transform-api) 这个变更造成的

**Comment by mwping** [comment]
Execution failed for task ':app:nuwaClassBeforeDexDebug'.

Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at cn.jiajixin.nuwa.NuwaPlugin$_apply_closure1_closure2_closure9_closure12.doCall(NuwaPlugin.groovy:127)
        at cn.jiajixin.nuwa.NuwaPlugin$_apply_closure1_closure2_closure9.doCall(NuwaPlugin.groovy:121)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more

**Comment by mwping** [comment]
@jasonross 你的插件脚本是在什么环境上编译的，我的windows上面用不了，是不是没有适配window？

**Comment by gondole** [comment]
Error:Execution failed for task ':xxx:nuwaClassBeforeDexDebug'.
> 1

请问这个问题如何解决？目前编译环境已经修改和nuwaDemo一样的了，demo可以运行没问题，集成到项目里一直报这个错。

**Comment by gondole** [comment]
Error:Execution failed for task ':xxx:nuwaClassBeforeDexDebug'. >1

请问这个问题如何解决？目前编译环境已经修改和nuwaDemo一样的了，demo可以运行没问题，集成到项目里一直报这个错。

**Comment by lguipeng** [comment]
主要是因为这个
Deprecated the dex getter from the ApplicationVariant class. You can't access the Dex task through the variant API anymore because it’s now accomplished through a transform. There's currently no replacement for controlling the dex process
