### ISSUE TITLE
java.lang.NoClassDefFoundError: cn.jiajixin.nuwa.Hack

### ISSUE THREAD

**Issue by liericiyan** [jasonross/Nuwa#16]
application继承的是MultiDexApplication，内部使用了静态变量okhttp 声明：   public static final OkHttpClient client = new OkHttpClient();
然后就报错了

**Comment by jasonross** [comment]
@liericiyan 看一下readme里，nuwa DSL的说明

**Comment by liericiyan** [comment]
不好意思，nuwa DSL的说明 我看不太明白

**Comment by jasonross** [comment]
nuwa{
excludeClass=['OkHttpClient.class']
}

把这个加在apply plugin 'cn.jiajixin.nuwa'的后面

**Comment by liericiyan** [comment]
## Sorry,It's useless! 

build.gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(":nuwa")
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:design:22.2.1'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.okio:okio:1.5.0'
}
apply plugin: "cn.jiajixin.nuwa"
nuwa{
    excludeClass=['OkHttpClient.class']

## }

The error log is: 
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: cn.jiajixin.nuwasample, PID: 21631
                                                   java.lang.NoClassDefFoundError: cn.jiajixin.nuwa.Hack
                                                       at a.a.a.r.<init>(Unknown Source)
                                                       at a.a.a.r.<clinit>(Unknown Source)
                                                       at a.a.a.p.<clinit>(Unknown Source)
                                                       at cn.jiajixin.nuwasample.NuwaApplication.<clinit>(Unknown Source)
                                                       at java.lang.Class.newInstanceImpl(Native Method)
                                                       at java.lang.Class.newInstance(Class.java:1214)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:990)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:525)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4403)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:142)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5118)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)

##                                                        at dalvik.system.NativeStart.main(Native Method)

The code is :
public class NuwaApplication extends Application {
    public static final OkHttpClient client = new OkHttpClient();
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        Nuwa.init(this);
        Nuwa.loadPatch(this, Environment.getExternalStorageDirectory().getAbsolutePath().concat("/patch.jar"));
    }
}

**Comment by jasonross** [comment]
@liericiyan 
继续看nuwa DSL的includePackage用法，看不懂就算了吧，要么改代码，静态初始化延迟。

**Comment by liericiyan** [comment]
延迟加载解决了这个问题，感谢！

**Comment by AllynYonge** [comment]
请问加载patch.jar时出现时，在BaseApplication初始化的时候出现
Class ref in pre-verified class resolved to unexpected implementation错误，是什么原因

**Comment by JakeWoki** [comment]
@liericiyan 延迟加载还是java.lang.NoClassDefFoundError: cn.jiajixin.nuwa.Hack
@jasonross includePackage、excludeClass都不能用啊

**Comment by gondole** [comment]
@jasonross 我试了试nuwa的sample是可以的，然后我加入了一个baseApplication 让NuwaApplication继承之，然后运行就会出现Hack类找不到的情况，你的什么情况？

**Comment by gondole-zz** [comment]
@JakeWoki 我试了试nuwa的sample是可以的，然后我加入了一个baseApplication 让NuwaApplication继承之，然后运行就会出现Hack类找不到的情况，你的什么情况？

**Comment by JakeWoki** [comment]
@gondole @jasonross 说看Nuwa DSL，使用 includePackage、excludeClass，不过我用不了

**Comment by dodola** [comment]
@gondole 你不会忘了加权限吧，我遇到个盆友就是忘了加权限(・・)

``` xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Comment by gondole-zz** [comment]
@dodola @JakeWoki 权限是没有问题的，只是给nuwaApplication添加了一个父类继承Application，仍会提示找不到Hack类，苦思摸索找原因中呢。。。另外DSL中说Application不用exclude 对吧。@JakeWoki 你试试加个继承application的父类给nuwaApplication继承试试啊。

**Comment by dodola** [comment]
@gondole 不知道这算不算个bug，出现这个问题是因为插件将你BaseApplication的构造方法里插入了        Class cls = Hack.class; 所以你应该将这个类排除在外

**Comment by JakeWoki** [comment]
@gondole 不用继承nuwaApplication，nuwaApplication没什么东西在里面，我项目Application本来就继承了别的

**Comment by dodola** [comment]
@gondole 如果excludeClass = ['BaseApplication.class'] 不能用的话，那么就不要混淆BaseApplication这个类

**Comment by gondole-zz** [comment]
@dodola @JakeWoki 问题已经解决。

解决方法就是dodola说的对baseApplication类移除混淆并且添加到excludeClass中。

@JakeWoki 这段代码nuwa {excludeClass = ['BaseApplication.class'] } 要和android {} 平级的。

@dodola 为什么要防止BaseApplication混淆呢？还望解答一下 :）

**Comment by JakeWoki** [comment]
Error:(114, 0) No such property: excludeClass for class: com.android.build.gradle.internal.dsl.BuildType_Decorated

@gondole @dodola 我这边提示这个

**Comment by dodola** [comment]
@gondole 因为作者是将打包后的jar包拿出来进行处理，这个时候已经是混淆的了，BaseApplication有可能已经变了名字比如a.class 这时候excludeClass的hashset里找不到a.class

**Comment by dodola** [comment]
@JakeWoki 写在apply plugin之后

``` groovy

apply plugin: "cn.jiajixin.nuwa"
nuwa{
    excludeClass = ['BaseApplication.class']

}
```

**Comment by JakeWoki** [comment]
@gondole @dodola 
apply plugin: "cn.jiajixin.nuwa"
nuwa{
    excludeClass = ['BaseApplication.class']

}
加上这个和去掉混淆了，但还是提示java.lang.NoClassDefFoundError: cn.jiajixin.nuwa.Hack
吐血了

**Comment by JakeWoki** [comment]
@gondole @dodola 可以加下qq不？137391455
一直报没找到的错误

**Comment by JakeWoki** [comment]
@jasonross @gondole @dodola 
nuwa {
    includePackage = ['com/activeandroid/',
                    'com/android/support/multidex']
    excludeClass = ['com/activeandroid/content/ContentProvider.class',
                    'com/activeandroid/DatabaseHelper.class']
}
java.lang.NoClassDefFoundError: cn.jiajixin.nuwa.Hack
            at com.activeandroid.content.ContentProvider.<init>(ContentProvider.java:18)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.app.ActivityThread.installProvider(ActivityThread.java:5267)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4873)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4756)
            at android.app.ActivityThread.access$1600(ActivityThread.java:171)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5679)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by dodola** [comment]
@JakeWoki 虽然看不出为啥，但com/activeandroid/content/ContentProvider.class 这个类应该被注入了hack.class了，ContentProvider类，你去掉混淆没

**Comment by JakeWoki** [comment]
@dodola 去掉混淆了，不过还是不行
java.lang.NoClassDefFoundError: cn.jiajixin.nuwa.Hack
at com.activeandroid.ModelInfo$1.<init>(ModelInfo.java:53)
at com.activeandroid.ModelInfo.<init>(ModelInfo.java:47)
at com.activeandroid.Cache.initialize(Cache.java:66)
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
at com.activeandroid.content.ContentProvider.onCreate(ContentProvider.java:39)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
at android.app.ActivityThread.installProvider(ActivityThread.java:5279)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:4873)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4756)
at android.app.ActivityThread.access$1600(ActivityThread.java:171)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5679)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)

**Comment by liericiyan** [comment]
@JakeWoki 可以试试另一个Andfix开源热修复，不需要重启app，addpatch之后立即生效

**Comment by JakeWoki** [comment]
@dodola 
nuwa {
    includePackage = ['com/activeandroid']
}
gradlew clean nuwaReleasePatch -P NuwaDir=F:/nuwa
这样执行BUILD SUCCESSFUL成功了，但是没有生成patch.jar，也没有相应的xxx.class生成
