### ISSUE TITLE
打release包开启混淆后Execution failed for task ':app:nuwaJarBeforeDexRelease'.

### ISSUE THREAD

**Issue by snzang** [jasonross/Nuwa#53]
FAILURE: Build failed with an exception.
14:42:24.897 [ERROR] [org.gradle.BuildExceptionReporter] 
14:42:24.897 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':basket:nuwaJarBeforeDexRelease'.
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter] > Source '/app/build/outputs/mapping/release/mapping.txt' does not exist
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter] 
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter] \* Exception is:
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':basket:nuwaJarBeforeDexRelease'.
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
14:42:24.898 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.io.FileNotFoundException: Source '/Users/roland/Downloads/trunk2/basket/build/outputs/mapping/release/mapping.txt' does not exist
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:637)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:607)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.commons.io.FileUtils$copyFile.call(Unknown Source)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at cn.jiajixin.nuwa.NuwaPlugin$_apply_closure1_closure2_closure7.doCall(NuwaPlugin.groovy:97)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
14:42:24.899 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
14:42:24.900 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
14:42:24.900 [ERROR] [org.gradle.BuildExceptionReporter]        ... 14 more
14:42:24.900 [ERROR] [org.gradle.BuildExceptionReporter] 
14:42:24.900 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:42:24.900 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
14:42:24.900 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:42:24.900 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 46.916 secs

**Comment by WPCWEG** [comment]
输出一下详细到Gradle编译的详细Info.查看是不是因为NuwaGradle这个编译项目里面NuwaPlugin.groovy或则是util/NuwaProcessor.groovy这个两个类报的数组越界错误。女娲坑太多，这只是一个Demo,不要运用在实际项目中。

**Comment by snzang** [comment]
@DoubleAngle 最终定位的原因是mapping文件没找到，不知道怎么回事 Caused by: java.io.FileNotFoundException: Source '/Users/.../build/outputs/mapping/release/mapping.txt' does not exist

**Comment by WPCWEG** [comment]
mapping是你在编译过程中就会生成的
