### ISSUE TITLE
三星note5 6.0 闪退 hack加入到dexlist失败

### ISSUE THREAD

**Issue by allenymt** [jasonross/Nuwa#77]
实测 华为机子5.0系统通过了，三星note5 6.0系统报错如下：
   Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jiajixin.nuwa.Hack" on path: DexPathList[[zip file "/data/app/cn.jiajixin.nuwasample-2/base.apk"],nativeLibraryDirectories=[/data/app/cn.jiajixin.nuwasample-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                            at cn.jiajixin.nuwasample.MainActivity.<init>(Unknown Source) 
                                                                            at java.lang.Class.newInstance(Native Method) 
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1095) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3084) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                            Suppressed: java.lang.ClassNotFoundException: cn.jiajixin.nuwa.Hack
                                                                            at java.lang.Class.classForName(Native Method)
                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

**Comment by allenymt** [comment]
hack加到dexlist失败
